apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /database-fake-setters
  name: root-package-setters
  annotations:
    config.kubernetes.io/local-config: 'true'
    internal.kpt.dev/upstream-identifier: '|ConfigMap|default|database-fake-setters'
data:
  frontend.image: krusonl.azurecr.io/chat-frontend:sha-c4e1dbf
  backend.image: krusonl.azurecr.io/chat-backend:sha-c4e1dbf
