apiVersion: v1
kind: Service
metadata:
  name: chat-backend
  labels:
    app: chat-backend
spec:
  selector:
    app: chat-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
