apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-backend-deployment
  namespace: event-12
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-backend
  template:
    metadata:
      labels:
        app: chat-backend
    spec:
      containers:
        - name: chat-backend
          image: krusonl.azurecr.io/chat-backend:sha-9cddb32
          ports:
            - containerPort: 8000
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-api-key-secret
                  key: OPENAI_API_KEY
          resources: {}
