
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: node-red-gateway
  namespace: test
spec:
  selector:
    istio: aks-istio-ingressgateway-external
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"