apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: streamlit-virtualservice
  namespace: event-12
spec:
  hosts:
    - "*"
  gateways:
    - generic-gateway
  http:
    - match:
        - uri:
            prefix: /streamlit
      route:
        - destination:
            host: streamlit-service
            port:
              number: 80