apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-deployment
  namespace: event-12
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
        - name: streamlit
          image: krusonl.azurecr.io/chat-frontend-streamlit:sha-a29ad50
          ports:
            - containerPort: 8501
          env:
          - name: STREAMLIT_SERVER_PORT
            value: "8501"
          - name: WEBSOCKET_URL
            value: "ws://52.155.92.36/ws"