
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-deployment
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
        - name: streamlit
          image: krusonl.azurecr.io/chat-frontend-streamlit:sha-7ff6e22
          ports:
            - containerPort: 8501
          envs:
            - name: STREAMLIT_SERVER_PORT
              value: "8501"
            - name: WEBSOCKET_URL
              value: "ws://52.155.92.36/ws"