apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-frontend
  namespace: event-12
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-frontend
  template:
    metadata:
      labels:
        app: chat-frontend
    spec:
      containers:
        - name: chat-frontend
          image: krusonl.azurecr.io/chat-frontend:sha-e586071
          ports:
            - containerPort: 8501
          env:
            - name: STREAMLIT_SERVER_PORT
              value: "8501"
            - name: WEBSOCKET_URL
              value: "wss://kruso-event-12.lelos.xyz/ws"
          resources: {}
