apiVersion: v1
kind: Service
metadata:
  name: chat-frontend-streamlit
  labels:
    app: chat-frontend-streamlit
spec:
  selector:
    app: chat-frontend-streamlit
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
