apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-frontend
  template:
    metadata:
      labels:
        app: chat-frontend
    spec:
      containers:
        - name: chat-frontend
          image: krusonl.azurecr.io/chat-frontend:sha-c4e1dbf # kpt-set: ${frontend.image}
          ports:
            - containerPort: 8501
          env:
            - name: STREAMLIT_SERVER_PORT
              value: "8501"
            - name: WEBSOCKET_URL
              value: "ws://10.15.224.190/ws"
          resources: {}
